Feature/new node object selection
WalkingMachine/wm_objects_selection pull request #1
Opened 2017-05-22 21:51 UTC by Fenrir12

Corrected nodes for better functionality.
Added subscibre to topic of object to find
Added publish of position of selected objct
Wrote launch file to test along with ork line mod server and client

2017-05-23 00:07 UTC, maximeconnolly requested changes

2017-05-23 00:07 UTC, maximest-pierre commented on CMakeLists.txt
> +  rcgnzd_obj.srv
Change to RecognizeObject.srv

2017-05-23 00:07 UTC, maximest-pierre commented on srv/rcgnzd_obj.srv
> +geometry_msgs/PoseWithCovarianceStamped SlctObjectPose
change to selected_object_pose

2017-05-23 03:24 UTC, Fenrir12 commented
Note : Error on ServerResponse. Always sends back the first element of the list and not the right element

2017-05-23 14:34 UTC, maximest-pierre commented on source/wm_obj_slct_srv.py
> +    return req.objectarray.objects[0].pose
There is the problem the index value of the array is hardcoded.

2017-05-24 03:44 UTC, Fenrir12 commented
Did the modifications and corrected the retrieved object bug. Latest commit 11013a3 ready to merge

2017-05-24 15:30 UTC, maximeconnolly approved these changes

2017-05-24 15:31 UTC, merged